apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: llama
