{
 "title": "LLAMA",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Avg prompt throughput, token/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llamacpp:prompt_tokens_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg generation throughput, token/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "llamacpp:predicted_tokens_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV-cache usage, %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llamacpp:kv_cache_usage_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "KV-cache tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llamacpp:kv_cache_tokens", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of request processing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llamacpp:requests_processing", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of request deferred",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "llamacpp:requests_deferred", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of prompt tokens processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "llamacpp:prompt_tokens_total", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Number of generation tokens processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "llamacpp:tokens_predicted_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Prompt process time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "llamacpp:prompt_seconds_total", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Predict process time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "llamacpp:tokens_predicted_seconds_total",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}