apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: llama-server
  labels:
    app: llama-server
spec:
  serviceName: llama-server
  replicas: 1
  selector:
    matchLabels:
      app: llama-server
  template:
    metadata:
      labels:
        app: llama-server
    spec:
      containers:
      - name: llama-server
        image: docker.io/intel/oneapi-runtime:2024.1.0-devel-ubuntu22.04 # docker.io/intel/oneapi-basekit:2024.0.1-devel-ubuntu22.04
        imagePullPolicy: IfNotPresent # Never  # only use a local image. If no local image is available, an exception occurs.
        command: ["/mnt/build/bin/server", "-m", "/mnt/models/gemma-2b.gguf", "-c", "512", "--host", "0.0.0.0", "--port", "8080", "--metrics"]
        ports:
        - name: llama-8080
          containerPort: 8080
        volumeMounts:
        - name: llama
          mountPath: /mnt
      volumes:
      - name: llama
        persistentVolumeClaim:
          claimName: llama
