apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: llama
  hostPath:
    path: "/home/admin/workdir/llama.cpp"
#  local:
#    path: /home/admin/workdir/llama.cpp
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - clr-25f03e9a66d5470280d2bb5f60e8dba1
