apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: llama
  hostPath:
    path: "/home/admin/workdir/llama.cpp"
