apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llama-metrics
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: llama-server
  endpoints:
  - port: llama-8080
    path: /metrics
    interval: 10s
    honorLabels: true

